### ISSUE TITLE
关于模型的问题

### ISSUE THREAD

**Issue by zhangxin253675** [YangParky/BASeg#3]
作者您好，非常感谢您出色的工作与code!
我在复现代码时，发现 baseg.py 中第447行，与您论文中似乎不一致；
期待作者解答，谢谢，祝您科研顺利！

这是下载得到的 baseg.py内容
![截图 2024-04-14 19-00-14](https://github.com/YangParky/BASeg/assets/109443346/a8c80863-60ba-4126-b10f-792f0c572685)

请问是不是应该修改成如下这样？
![截图 2024-04-14 19-07-08](https://github.com/YangParky/BASeg/assets/109443346/3088b4a3-d6d3-4af5-af5d-a74c2fcf38c5)

**Comment by YangParky** [comment]
> 期待作者解答，谢谢，祝您科研顺利！

谢谢您对该工作的关注，由于之前忘记公开了，前不久才注意到。但由于时间有点久，细微处可能存在纰漏。

感谢您的指正，我已经修改了，具体请看model/baeg.py，祝您科研顺利~
