### ISSUE TITLE
关于通过模型的层的输入通道数对不上的问题

### ISSUE THREAD

**Issue by UltramanTheInvincibleUniverse** [YangParky/BASeg#4]
尊敬的作者您好！
我对您的工作十分感兴趣，但我发现一些问题
这个层的期望输入通道数是2048，但实际输出通道数是2560
![图片](https://github.com/YangParky/BASeg/assets/148739186/50470c85-a7f1-4036-af8c-c37731b80520)
您的这份代码是完整的吗，能够正常运行的吗
期待您的回复

**Comment by UltramanTheInvincibleUniverse** [comment]
我把那个层的输入通道数改成2560后项目可以开始训练了，但一开始梯度爆炸这个正常的吗
![图片](https://github.com/YangParky/BASeg/assets/148739186/05509ab4-1991-4b5d-a2bf-b0d851cdbcd0)
期待您的回复

**Comment by YangParky** [comment]
您好，感谢你对该工作的关注，这里确实没有改过来，已经修改后提交~

由于我训练的时候是4张2/1080 TI，训练比较吃力，所以我当时用了apex的混合精度训练。您可以注释掉混合精度，具体如图所示；同时建议这边batch size可以适当调大一点如果仍然还有的话。
![image](https://github.com/YangParky/BASeg/assets/38532963/c18b6a49-1982-4ab1-8578-3a461b75688b)

**Comment by UltramanTheInvincibleUniverse** [comment]
> 您好，感谢你对该工作的关注，这里确实没有改过来，已经修改后提交~
> 
> 由于我训练的时候是4张2/1080 TI，训练比较吃力，所以我当时用了apex的混合精度训练。您可以注释掉混合精度，具体如图所示；同时建议这边batch size可以适当调大一点如果仍然还有的话。 ![image](https://private-user-images.githubusercontent.com/38532963/322852218-c18b6a49-1982-4ab1-8578-3a461b75688b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMyNzI5NTMsIm5iZiI6MTcxMzI3MjY1MywicGF0aCI6Ii8zODUzMjk2My8zMjI4NTIyMTgtYzE4YjZhNDktMTk4Mi00YWIxLTg1NzgtM2E0NjFiNzU2ODhiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE2VDEzMDQxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJjYzQxYjIyM2VjNjcxYzhjMzY0MzUwZTYzNjA0YmFkZGRjNjRkZWNjMzI2Y2JmMTFlNDE2YTk2YmRkNWEzMjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.EI73Ra4aNiSkAtKgKtiNiKXdbanbJVFHZEfNJLMtMrU)

感谢您的回复，我一开始用的单卡p40，然后提示显存不足所以把batch size调小了。
祝您学术长青！
