### ISSUE TITLE
关于聚合模块的中间通道数和监督边界流的标签bound

### ISSUE THREAD

**Issue by UltramanTheInvincibleUniverse** [YangParky/BASeg#5]
尊敬的作者您好！
您研究方法的思路我非常感兴趣，我想请教您一些问题，如果您在方便的时候给予回答，我将不胜感激。
关于这个聚合语义流和边界流模块的中间通道设置有什么要求吗，如果我的语义流通道数是480，类别数是2的话我中间通道数应该设置多少比较合理？
![图片](https://github.com/YangParky/BASeg/assets/148739186/2f3df830-9248-453a-a438-1a20b77beb69)

这个监督边界流的标签bound应该怎么处理，是将原本的真实值标签做Canny处理或者二值化作为边界流的标签吗？
![图片](https://github.com/YangParky/BASeg/assets/148739186/4f8072fa-789a-43ca-a19d-426d1690eb4d)
如果您觉得方便的话，我将引用您的论文。
期待您的回复
祝您万事如意，学术长青！

**Comment by YangParky** [comment]
首先，语义聚合流模块的目的是使得模型获得边界和语义分割增益，中间通道应该还是设置为1；由于canny都得到的是[B 1 H W]的数组，在与高级语义信息融合的同时，我是将F1‘降维融合，当然你也可以使B1升维试试；

其次，关于边界bound标签问题。bound标签的生成在util/dataset.py里有，make_bound_dataset就是生成边界的函数，具体使用方法其实我已经放在dist_help.py里，您可以注释回来；

另外，canny的作用是用于产生一个先验粗糙的边界轮廓，对于给定的图像，阈值设定好后其提取的特征是固定的。因此梯度回传的时候，优化的是到BRM模块为止。在此处，我们结合bound标签并使用二值交叉熵来监督。希望我的回复能对你有所帮助~

**Comment by UltramanTheInvincibleUniverse** [comment]
> 首先，语义聚合流模块的目的是使得模型获得边界和语义分割增益，中间通道应该还是设置为1；由于canny都得到的是[B 1 H W]的数组，在与高级语义信息融合的同时，我是将F1‘降维融合，当然你也可以使B1升维试试；
> 
> 其次，关于边界bound标签问题。bound标签的生成在util/dataset.py里有，make_bound_dataset就是生成边界的函数，具体使用方法其实我已经放在dist_help.py里，您可以注释回来；
> 
> 另外，canny的作用是用于产生一个先验粗糙的边界轮廓，对于给定的图像，阈值设定好后其提取的特征是固定的。因此梯度回传的时候，优化的是到BRM模块为止。在此处，我们结合bound标签并使用二值交叉熵来监督。希望我的回复能对你有所帮助~

万分感谢作者的回复！
