### ISSUE TITLE
ImageNet pre-trained models & trained segmentation models needed!

### ISSUE THREAD

**Issue by SchumacherVonHeinz** [YangParky/BASeg#6]
The download link you provided is no longer valid, and the page shows that drive.google.com has closed the connection.
您提供的下载链接已失效，页面显示drive.google.com 关闭了连接。

**Comment by YangParky** [comment]
Apologies for the late reply, but the link still works when I opened it. 
![1734595973162](https://github.com/user-attachments/assets/308e435e-281d-42c2-a67b-d95dd2335023)

**Comment by SchumacherVonHeinz** [comment]
Thank you for your answer, it seems that there is some problem with my network. Even if I use the VPN, I can not open the link. Anyway, I have found another solution, thank you again for your attention.
